### ISSUE TITLE
Create input standardizer to preprocess audio data

### ISSUE THREAD

**Issue by yosoyjay** [axiom-data-science/OrcaCNN#1] opened 2019-03-19 18:33 UTC
The primary job of this tool is to detect orca in passive acoustic datasets comprised of a pipeline consisting of stages to: 1) preprocess and standardize input data, 2) apply a model to identify the presence of orca within the dataset, 3) apply additional models to extract additional information about the orca call including signal type and pod, and 4) create a summary of the results of the pipeline indicating presence of orca along with time and any additional information.

The issue here is to develop part 1 of the pipeline to develop both the format of the standardized data and the tool to create such a dataset.

**Comment by kunakl07** [comment] 2019-03-19 19:22
Hi @yosoyjay,

Sir,I have created and hosted a website on [000webhost](http://tublikaru9999.000webhostapp.com/) which would preprocess and standardize the input data.
The  output standard I have chosen here is .wav format.
The sample audio calls in any format could be given as an input to the site and it would convert it to standard .wav format.
This .wav file could be downloaded from the options and can be passed to our model for part2.
Sir,what would be the  futher improvements that I should add in 1st part?

**Comment by yosoyjay** [comment] 2019-03-19 20:14
@kunakl07 Thanks!  I believe all of the files we will receive will already be in a .wav format, but the main issue is that they will be varying lengths and perhaps encoded with different bit rates and such. So the idea here is that those files will need to be encoded in a standard way and then divided up so that all of the samples are of the same length.

Also, although eventually we want a frontend for a researcher to be able to upload a file.  We'll actually want this part of the processing to work via a command line interface and a REST API.

**Comment by kunakl07** [comment] 2019-03-19 20:52
Okay sir, thanks. 
Will surely add the necessary changes.

**Comment by ZER-0-NE** [comment] 2019-03-21 19:02
Hi @yosoyjay 
On visualizing the data which you provided as an example, we see that the distribution of audio length across labels is non-uniform and has very high variance. 

![Screenshot from 2019-03-21 23-45-07](https://user-images.githubusercontent.com/19359908/54775276-a95d0700-4c33-11e9-92c6-0dd147659b4d.png)

Also, the frame length distribution shows that majority of the audio files are short and there might be some outlier that exist in the dataset.

![Screenshot from 2019-03-21 23-45-59](https://user-images.githubusercontent.com/19359908/54775616-60598280-4c34-11e9-84d4-1b5dcab28caf.png)

Now, naturally the question arises that:
1) Can we ignore the outliers (if less in number) or maybe manually check on them? I believe the size of the dataset would be huge and manually looking after the outliers is a hard choice.
2) The preprocessing step would involve standardizing the audio frame distribution(Fig 1). Do we have a particular length for number of frames? 
3) I was considering the audio length to be product of the sampling rate and the audio duration. What do we take as the audio duration? I guess all audio files can be padded or can be shrunk to a particular size. I was wondering is there a standard format for this or we simply listen to our intuition?

**Preprocessing**
1) To remove silences from audio files by normalizing all signals by amplitude (divide by abs(max(signal))). Also, we would set an amplitude threshold so that we throw out any signal below that threshold.
2) Sliding window STFT: We will choose a window size based on the sampling rate and the frequency content of the dataset since we want windows to be long enough to capture the lowest relevant frequency content while being short enough that we don't miss much of the time-variance.
3) For bitrate, two things go hand in hand: Sampling Frequency and BitDepth.
It would be easier to have the same sampling rate for all the audio signals and we would downsample all our signals to the lowest sampling frequency.
As for bit depth, it shouldn't be a problem since we'll be converting the amplitude values to float before running STFT. I don't think it should matter much, but to be absolutely sure, we can use the same approach as downsampling and "down-quantize" everything to the lowest bit depth in the dataset.

Mainly, resampling and normalization should work to standardize our data along with the three steps I mentioned above.

Next, once we have a standard data of fixed length and duration, we would work on the spectrogram images of all those samples. We would mainly,
1) Enhance contrast and denoise. Weiner filter is also a good choice.
2) Focus on lower frequency range (100Hz - 200Hz) where orca calls exist.

Do let me know your thoughts on the pipeline I mentioned above @yosoyjay and correct me if I'm wrong. I will share the code if you'd like to.

**Comment by kunakl07** [comment] 2019-03-22 14:02
Hi @yosoyjay ,
I have created an API [KunalmehtaXD.pythonanywhere.com](http://KunalmehtaXD.pythonanywhere.com/)  on Flask and hosted it using pythonanywhere.This REST-API would convert and encode the long audio files of any length and divide these into standard sized chunks of same length(here I have taken standard size as 4 seconds).This chunks would be stored in my downloads folder as 
![divided](https://user-images.githubusercontent.com/36035718/54828353-3b373500-4c71-11e9-8dd9-5f01b9926462.jpg)


These chunks would be have standard size and bit-rate of 1411kbps(44100 Hz, 16 bit stereo).
We can also this tool (of encoding and dividing) from command line.

![command_line](https://user-images.githubusercontent.com/36035718/54828378-48ecba80-4c71-11e9-9466-9de96e23273a.jpg)

In this example,as we can see that the large audio file is encoded and divided into 9 standard chunks of 4 sec each with each having standard bit-rate of 1411kbps(44100 Hz, 16 bit stereo).

Sir,
As you asked for,I have created a front-end and a REST-API that would encode and standardize any audio into same bit-rates and same length chunks and save them.
What would be the further improvements to be added?
These chunks would then be passed from my downloads folder to the next stage where detection of Ocra-calls would be done.

**Comment by yosoyjay** [comment] 2019-03-25 16:45
@ZER-0-NE Yeah, the samples I provided certainly did not constitute a uniform distribution.  And, certainly the real data will not either.  Like many natural phenomenon, I imagine that the distribution of labels will form a right-tailed distribution.  I wouldn't focus on the different lengths of the raw audio samples, they will vary tremendously, that's why it's important to standardize them.  I recommend taking another look at what the Google/NOAA group did for data pre-processing.

**Comment by yosoyjay** [comment] 2019-03-25 16:46
@kunakl07 Yup, this is pretty much what I had in mind.  However, as I mentioned to @ZER-0-NE, take another look at what the Google/NOAA group did for data pre-processing.  In particular look at the length of the samples they were evaluating.

**Comment by kunakl07** [comment] 2019-03-25 16:50
@yosoyjay 
Yeah. Sure sir

**Comment by sainimohit23** [comment] 2019-03-25 18:18
@yosoyjay I have a doubt regarding the standard size of audio data. @kunakl07 's algorithm is dividing the data in 4 second chunks. And I assume that 4 sec is also the input size of his model. But, the model I'm working on does not require the data to be divided into chunks. So, what should be the standard size of input audio in my case?

**Comment by kunakl07** [comment] 2019-03-25 19:07
Hi @sainimohit23 ,
As @yosoyjay said, the size of the  raw audio will vary tremendously, and the model will have a very hard time predicting Postive calls from a large audio file,so it would be a good idea to standardize your data and then divide it into same length chunks and feed this dataset as an input to your model .
I also believe that in order to predict different classes of calls in long samples, you need to divide the long audio segment into fixed sized chunks such that each class is correctly identified even when the interval between two different class is small.

**Comment by kunakl07** [comment] 2019-03-26 18:44
Hi @yosoyjay,
I have created a tool that would standardize any input data.
![bandicam 2019-03-26 11-27-34-631 (2)](https://user-images.githubusercontent.com/36035718/55023711-a5760f80-4fba-11e9-92a3-c70ac98625d3.jpg)
This is the audio file before standardization, I have converted this audio file into numpy array. After processing this numpy array, it is then standardized data using scikit learn library.
This is the image of standardized audio files
![bandicam 2019-03-26 11-27-20-117 (2)](https://user-images.githubusercontent.com/36035718/55023991-2c2aec80-4fbb-11e9-9e83-707b2945fbd2.jpg)
As we can see from this example that standardization of data has caused a huge impact by plotting all the data points within a specific range and unlike the previous one(where the few data points are scattered at a very large distance from the mean)
Once this audio data is standardized it would be divided into same length chunks which could be then fed to our first model for detection of calls.
@yosoyjay , Sir is the first stage complete? 
Please suggest further improvements.

**Comment by yosoyjay** [comment] 2019-03-26 19:45
@kunakl07, it's difficult to say if the first stage is "complete" because no code has been published and it is has not been tested with real data.  Also, remember that it is fine if the code is developed in Jupyter Notebooks, but it must eventually be transitioned to Python package.

It's impossible for me to assess what the effects of the normalization scheme that you are using because the plots you attached are missing critical pieces of information like: title, axes labels, units, etc.  In these kinds of situations it's critical to describe the algorithm with either the specific code written in `markdown` or to describe it using math.

**Comment by kunakl07** [comment] 2019-03-26 21:53
Hi @yosoyjay,
Sir, Initially, the audio files in the .wav format are converted into mfcc(padded if the maximum length exceeds mfcc length) and then saved as numpy arrays.
Now, this numpy array has three dimensions and for standardizing we need two dimensions, therefore we would convert it into two dimensions by taking a for loop and applying a standard scalar function(of sklearn that would standardize by removing mean and scaling to unit variance) to the 1st dimension and then the remaining ones.
Now since we have standardized them, we will convert them into three dimension array(which will be in standardized form).
Now, we will plot the 3D graph using matplotlib to show the difference between standardized and non-standardized audio. 
Sir, I have shared with you the colab notebook, added axes label, and title.
![bandicam 2019-03-26 14-47-04-360](https://user-images.githubusercontent.com/36035718/55035920-5dfd7c80-4fd6-11e9-9f6c-774c736892f2.jpg)
@yosoyjay ,Sir,Please suggest further improvements.

**Comment by yosoyjay** [comment] 2019-03-28 16:48
@kunakl07 So, it's not totally clear exactly how you are standardizing.  You have an m x n x p sized array, how exactly are you standardizing?  Over which dimensions?  Is there are particular reason you are not standardizing over the entire array?

Again, to be explicit, write the code down in markdown here so there is no ambiguity in what you are doing.

**Comment by kunakl07** [comment] 2019-03-28 19:10
Hi @yosoyjay
Yea sir in the above example,I had m x n x p sized array 
where
m=Signal
n=Rate
z=mfcc_feat
and I standardized only on Rate dimension(n dimension) as I thought we only wanted to standardized rate, there is no particular reason.
And sir, the reason for using for loop is that the Standard Scalar function of sklearn takes only two dimensions as input parameter and here we have three.
So, to standardize the entire array of three Dimension (m x n x p) over we need to take three for loop, and standardize each dimension in a single loop.
```python

!git clone https://github.com/axiom-data-science/OrcaCNN-data
import librosa
import os
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
import numpy as np
from tqdm import tqdm

DATA_PATH = "/content/OrcaCNN-data/data/training/"

##Converting .wav-->mfcc-->numpy array
### Input: Folder Path
### Output: Tuple (Label, Indices of the labels, one-hot encoded labels)
def get_labels(path=DATA_PATH):
    labels = os.listdir(path)
    label_indices = np.arange(0, len(labels))
    return labels, label_indices, to_categorical(label_indices)


# ##Handy function to convert wav2mfcc
def wav2mfcc(file_path, max_len=11):
    wave, sr = librosa.load(file_path, mono=True, sr=None)
    wave = wave[::3]
    mfcc = librosa.feature.mfcc(wave, sr=16000)

    # ##If maximum length exceeds mfcc lengths then pad the remaining ones
    if (max_len > mfcc.shape[1]):
        pad_width = max_len - mfcc.shape[1]
        mfcc = np.pad(mfcc, pad_width=((0, 0), (0, pad_width)), mode='constant')

    ### Else cutoff the remaining parts
    else:
        mfcc = mfcc[:, :max_len]
    
    return mfcc

###saving data to array
def save_data_to_array(path=DATA_PATH, max_len=11):
    labels, _, _ = get_labels(path)

    for label in labels:
        ### Init mfcc vectors
        mfcc_vectors = []

        wavfiles = [path + label + '/' + wavfile for wavfile in os.listdir(path + '/' + label)]
        for wavfile in tqdm(wavfiles, "Saving vectors of label - '{}'".format(label)):
            mfcc = wav2mfcc(wavfile, max_len=max_len)
            mfcc_vectors.append(mfcc)
        np.save(label + '.npy', mfcc_vectors)


def get_train_test(split_ratio=0.6, random_state=42):
    ### Get available labels
    labels, indices, _ = get_labels(DATA_PATH)

    # ##Getting first arrays
    X = np.load(labels[0] + '.npy')
    y = np.zeros(X.shape[0])

   ## # Append all of the dataset into one single array, same goes for y
    for i, label in enumerate(labels[1:]):
        x = np.load(label + '.npy')
        X = np.vstack((X, x))
        y = np.append(y, np.full(x.shape[0], fill_value= (i + 1)))

    assert X.shape[0] == len(y)

    return train_test_split(X, y, test_size= (1 - split_ratio), random_state=random_state, shuffle=True)



def prepare_dataset(path=DATA_PATH):
    labels, _, _ = get_labels(path)
    data = {}
    for label in labels:
        data[label] = {}
        data[label]['path'] = [path  + label + '/' + wavfile for wavfile in os.listdir(path + '/' + label)]

        vectors = []

        for wavfile in data[label]['path']:
            wave, sr = librosa.load(wavfile, mono=True, sr=None)
           ## # Downsampling
            wave = wave[::3]
            mfcc = librosa.feature.mfcc(wave, sr=16000)
            vectors.append(mfcc)

        data[label]['mfcc'] = vectors

    return data


def load_dataset(path=DATA_PATH):
    data = prepare_dataset(path)

    dataset = []

    for key in data:
        for mfcc in data[key]['mfcc']:
            dataset.append((key, mfcc))

    return dataset[:100]

```
remove json file for a timing
```
rm /content/OrcaCNN-data/data/training/positive/class_labels.json
```
```python




import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
from keras.utils import to_categorical

### Second dimension of the feature is dim2
feature_dim_2 = 11

### Save data to array file first
save_data_to_array(max_len=feature_dim_2)

### Loading train set and test set
X_train, X_test, y_train, y_test = get_train_test()

### Feature dimension
feature_dim_1 = 20
channel = 1
epochs = 1200
batch_size = 100
verbose = 1
num_classes = 2

### Reshaping to perform 2D convolution
X_train = X_train.reshape(X_train.shape[0], feature_dim_1, feature_dim_2, channel)
X_test = X_test.reshape(X_test.shape[0], feature_dim_1, feature_dim_2, channel)

y_train_hot = to_categorical(y_train)
y_test_hot = to_categorical(y_test)

```
```python
#Without Standardization

values=np.load("/content/positive.npy")

x=values[0]
y=values[1]
z=values[2]

from matplotlib.ticker import LinearLocator, FormatStrFormatter

import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()

ax = fig.gca(projection='3d')

R = np.sqrt(x**2 + y**2)
ax.set_xlabel("$Rate",fontsize=20)
ax.set_ylabel("Quality",fontsize=20)
ax.set_zlabel("Z",fontsize=15)
surf = ax.plot_surface(x, y, z, cmap=cm.coolwarm,
                       linewidth=0, antialiased=False)
ax.zaxis.set_major_locator(LinearLocator(10))
ax.zaxis.set_major_formatter(FormatStrFormatter('%.02f'))
ax.set_xlabel("Signal",fontsize=20)
ax.set_ylabel("Rate",fontsize=20)
ax.set_zlabel("mfcc_feat",fontsize=15)# Add a color bar which maps values to colors.
fig.colorbar(surf, shrink=0.5, aspect=5)

plt.show()

values=np.load("/content/positive.npy")
```

![bandicam 2019-03-28 10-44-27-635](https://user-images.githubusercontent.com/36035718/55185343-63330680-5151-11e9-8412-2dc60986a0a2.jpg)


```python
#With standardization
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from math import sqrt
values=np.load("/content/positive.npy")
X_train=values

##Standardizing each numpy array using StandardScalar function 

scalers = {}
###standardizing n where n is Rate
for i in range(X_train.shape[2]):
    scalers[i] = StandardScaler()
    X_train[:, i, :] = scalers[i].fit_transform(X_train[:, i, :]) 
###standardizing m where m is Signal 
for i in range(X_train.shape[2]):
    scalers[i] = StandardScaler()
    X_train[i, :, :] = scalers[i].fit_transform(X_train[i, :, :]) 
###standardizing p where p is mfcc_feat
for i in range(X_train.shape[2]):
    scalers[i] = StandardScaler()
    X_train[:, :, i] = scalers[i].fit_transform(X_train[:, :, i])     

x=X_train[0]
y=X_train[1]
z=X_train[2]
##Now once standardize we are going to plot using matplotlib
from matplotlib.ticker import LinearLocator, FormatStrFormatter

import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()

ax = fig.gca(projection='3d')
R = np.sqrt(x**2 + y**2)

surf = ax.plot_surface(x, y, z, cmap=cm.coolwarm,
                       linewidth=0, antialiased=False)

ax.zaxis.set_major_locator(LinearLocator(10))
ax.zaxis.set_major_formatter(FormatStrFormatter('%.02f'))
ax.set_xlabel("Signal",fontsize=20)
ax.set_ylabel("Rate",fontsize=20)
ax.set_zlabel("mfcc_feat",fontsize=15)
### Add a color bar which maps values to colors.
fig.colorbar(surf, shrink=0.5, aspect=5)
plt.title('Standardized data')

plt.show()
```
![bandicam 2019-03-28 11-59-39-648](https://user-images.githubusercontent.com/36035718/55185425-8bbb0080-5151-11e9-8929-e738c71ee8a8.jpg)
Sir, I have commented the code and this is the output graph after standardization is preformed on three dimensions.
@yosojay,
Please suggest if there is any ambiguity, 
Also here is the link to the jupyter notebook to perform [standardization](https://colab.research.google.com/drive/1PSVpmwdmsIlhrAH8eUvuUq2usGq_CscM) which runs on colab.

**Comment by yosoyjay** [comment] 2019-03-29 20:18
@kunakl07 Thank you for posting this way, it's much easier for me to understand to important parts like how you were doing the standardization and why you chose to standardize the way you did.  It's a balance, and I suppose a learned skill, to capturing and posting the kernel of the computation.

So, I know that the sci-kit learn standardizer assumes a 2D array, that's why I asked.  It's pretty straight-forward to standardize an N-dim array tho.  More relevantly, the question I was getting at was do the different standardization approaches affect the the results?

**Comment by kunakl07** [comment] 2019-03-29 22:01
Hi @yosoyjay,
Yes, sir,sci-kit learn standardizer assumes 2D array, so I converted our 3D array into 2D one.
Sir, I haven't checked how different standardization approaches affect the results in different ways, but will surely check the impact of different standardization methods on the result
Thank you, sir, for the feedback.

**Comment by kunakl07** [comment] 2019-03-30 01:39
Hi @yosoyjay ,
Now, I have standardized through MinMaxScalar.This is another method of standardization where the estimator scales and translates each feature individually such that it is in the given range on the training set.
Here is the code and its output generated
```python
#With standardization
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from math import sqrt
from sklearn.preprocessing import MinMaxScaler
values=np.load("/content/positive.npy")
X_train=values

##Standardizing each numpy array using MinMaxScalar function 
#scaler = MinMaxScaler()
min_max_scaler = preprocessing.MinMaxScaler()
scalers={}


###standardizing n where n is Rate
for i in range(X_train.shape[2]):
  
    scalers[i] = MinMaxScaler()
    X_train[:, i, :] = scalers[i].fit_transform(X_train[:, i, :]) 
###standardizing m where m is Signal 
for i in range(X_train.shape[2]):
    scalers[i] = MinMaxScaler()
    X_train[i, :, :] = scalers[i].fit_transform(X_train[i, :, :]) 
###standardizing p where p is mfcc_feat
for i in range(X_train.shape[2]):
    scalers[i] = MinMaxScaler()
    X_train[:, :, i] = scalers[i].fit_transform(X_train[:, :, i])     

x=X_train[0]
y=X_train[1]
z=X_train[2]
##Now once standardize we are going to plot using matplotlib
from matplotlib.ticker import LinearLocator, FormatStrFormatter

import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()

ax = fig.gca(projection='3d')
R = np.sqrt(x**2 + y**2)

surf = ax.plot_surface(x, y, z, cmap=cm.coolwarm,
                       linewidth=0, antialiased=False)

ax.zaxis.set_major_locator(LinearLocator(10))
ax.zaxis.set_major_formatter(FormatStrFormatter('%.02f'))
ax.set_xlabel("Signal",fontsize=20)
ax.set_ylabel("Rate",fontsize=20)
ax.set_zlabel("mfcc_feat",fontsize=15)
### Add a color bar which maps values to colors.
fig.colorbar(surf, shrink=0.5, aspect=5)
plt.title('Standardized data')

plt.show()
```
![bandicam 2019-03-29 18-37-38-843](https://user-images.githubusercontent.com/36035718/55269548-f05d8480-5251-11e9-8d9e-a3460178fe76.jpg)

The values are scaled between 0 and 1 by using foll. formulae
X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_scaled = X_std * (max - min) + min
Sir,I will check different standardization methods apart from this and compare their results

**Comment by kunakl07** [comment] 2019-03-30 03:56
Hi @yosoyjay ,
Here ,I have standardized through  MaxAbsScalar(maximum absolute value)
In this method,the estimator scales and translates each feature individually such that the maximal absolute value of each feature in the training set will be 1.0

```python

from sklearn.preprocessing import MaxAbsScaler
#With standardization
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from math import sqrt
from sklearn.preprocessing import MinMaxScaler
values=np.load("/content/positive.npy")
X_train=values

##Standardizing each numpy array using MaxAbsScalarfunction 
#scaler = MinMaxScaler()
min_max_scaler = preprocessing.MaxAbsScaler()
scalers={}


###standardizing n where n is Rate
for i in range(X_train.shape[2]):
  
    scalers[i] = MaxAbsScaler()
    X_train[:, i, :] = scalers[i].fit_transform(X_train[:, i, :]) 
###standardizing m where m is Signal 
for i in range(X_train.shape[2]):
    scalers[i] = MaxAbsScaler()
    X_train[i, :, :] = scalers[i].fit_transform(X_train[i, :, :]) 
###standardizing p where p is mfcc_feat
for i in range(X_train.shape[2]):
    scalers[i] = MaxAbsScaler()
    X_train[:, :, i] = scalers[i].fit_transform(X_train[:, :, i])     

x=X_train[0]
y=X_train[1]
z=X_train[2]
##Now once standardize we are going to plot using matplotlib
from matplotlib.ticker import LinearLocator, FormatStrFormatter

import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()

ax = fig.gca(projection='3d')
R = np.sqrt(x**2 + y**2)

surf = ax.plot_surface(x, y, z, cmap=cm.coolwarm,
                       linewidth=0, antialiased=False)

ax.zaxis.set_major_locator(LinearLocator(10))
ax.zaxis.set_major_formatter(FormatStrFormatter('%.02f'))
ax.set_xlabel("Signal",fontsize=20)
ax.set_ylabel("Rate",fontsize=20)
ax.set_zlabel("mfcc_feat",fontsize=15)
### Add a color bar which maps values to colors.
fig.colorbar(surf, shrink=0.5, aspect=5)
plt.title('Standardized data')

plt.show()
```
![bandicam 2019-03-29 20-54-27-229](https://user-images.githubusercontent.com/36035718/55271118-0d4f8300-5265-11e9-9c41-8a39df51335d.jpg)

**Comment by kunakl07** [comment] 2019-03-30 04:38
Hi @yosoyjay ,Sir similarly we can standardize using `RobustScalar` method by importing `RobustScaler` and replacing `MaxAbsScalar` by `RobustScalar` and the standarized output graph would be
![bandicam 2019-03-29 21-15-24-062](https://user-images.githubusercontent.com/36035718/55271307-fd856e00-5267-11e9-8de9-819a664c04b1.jpg)

In this method the Scaler removes the median and scales the data according to the quantile range.


Similarly,we can use Normalizer by importing it and replacing `MaxAbsScalar` by `Normalizer`.Here,we normalize each sample individually.
The normalized graph would be:
![bandicam 2019-03-29 21-07-42-327](https://user-images.githubusercontent.com/36035718/55271312-2148b400-5268-11e9-94f6-20fbc7169569.jpg)

Similarly, we can standardize using QuantileTransformer by importing and replacing `Normalizer` by `QuantileTransformer`.
This method transforms the features to follow a uniform or a normal distribution. Therefore, for a given feature, this transformation tends to spread out the most frequent values. It also reduces the impact of (marginal) outliers: this is therefore a robust preprocessing scheme.
![bandicam 2019-03-29 21-30-25-872](https://user-images.githubusercontent.com/36035718/55271446-fc554080-5269-11e9-8874-55a386267275.jpg)

Similarly,Standardization using ` PowerTransformer` is done by replacing `QuantileTransformer` by `Power Transformer`.
Power transforms are a family of parametric, monotonic transformations that are applied to make data more Gaussian-like.
![bandicam 2019-03-29 21-32-21-318](https://user-images.githubusercontent.com/36035718/55271515-f875ee00-526a-11e9-91e2-bc66cd6b0475.jpg)

**Comment by kunakl07** [comment] 2019-03-30 04:56
Sir, I think that MaxAbsScalar would produce a comparatively effective standardized result (even for the large datasets)as the volume is bit evenly spread within a small range of values as compared to other standardization techniques.

**Comment by ZER-0-NE** [comment] 2019-04-12 17:13
Hi @yosoyjay 
These are the pre-processing steps I've mentioned in my proposal and also coded out in my demo version. I've marked them as either Done or Discarded accordingly with the references mentioned.
Summarising,

1. Resampling to a sampling frequency of 44100.
2. Padding to get fixed-size samples
3. Applied PCEN (as was done by Google/NOAA)
4. Applied Wavelet Denoising instead of Spectral Subtraction method (as it improved SNR ratio as well which is important for hydrophone data).

**Steps mentioned:**

- Resampling and normalization of all the audio samples: Since the sampling rates of all the audio samples will be different, we will resample all the audio files to a specific sampling frequency. [Done]

- Data Augmentation techniques for padding of samples. [Added]

- Removing all the dead samples (negligible frequency)(if any) from the dataset. [Not yet applicable, samples can be removed by observing their sampling rate]

- Denoising: We use Spectral-Subtraction method to reduce background noise. This method is based on spectral averaging and residual noise reduction, widely used for enhancement of noisy speech signals and can remove the stationary noise included in the sound. The Wiener filter is also an option. [Discarded because wavelet denoising is a better choice].

- We prepare spectrogram images with Linear Short Time Fourier Transform/Log-Mel Filter Bank features using Python. Librosa will be the preferred choice for computing these feature representations.[Done]

- Contrast Enhancement: From past experience, Histogram Equalization has been found as a better option than capping the extreme values to mean ± 1.5 std. [On hold]

- Focusing on Low-Frequency Spectrum: The whale calls are normally found in the lower frequency spectrum ranging from 100Hz-200Hz. This would allow us to look only at the specific part of the image which will be beneficial to the CNN architecture when given as input. The rest of the image part would roughly count as “noise” (or irrelevant) portion for CNN.[Will be done as last pre-processing step]

- Signal to Noise (SNR) Ratio: It is essential to have a high value of SNR for all the audio samples. Previous kaggle competition have shown this as an essential factor in improving the model accuracy.[Wavelet Denoising improves SNR]

- Hydrophone data are subject to a variety of in-band noise sources. A band-pass filter is a simple way to remove unwanted noise outside of the signal frequency band. **Wavelet denoising is an effective method for SNR improvement in environments with wide range of noise types competing for the same subspace.**

- **To improve robustness to loudness variation, per-channel energy normalization (PCEN) was found better than the standard log-mel frontend (and even with an optimized spectral subtraction process).** This provided a 24% reduction in error rate of whale call detection. It also helps in reducing the narrow-band noise which is most often caused by nearby boats and the equipment itself.[Done]

**Comment by ZER-0-NE** [comment] 2019-07-16 06:39
#8 has been developed. Closing this

**Closed as completed by ZER-0-NE** 2019-07-16 06:39 UTC
